DEDS-157,EIP_EX????_RC_MPU_?.??_DNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_BAC_?.??_DNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_BAC_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_CST_?.??_DNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_CST_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_AST_?.??_DNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_AST_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_CST_?.??_DNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_CST_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_CNTRY_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_PYMNTMHD_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_BILLMEDIA_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_EX????_RC_PRODSPEC_?.??_MNH_?_?_????????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-157,EIP_KOGN_RC_CONTROL_FILE_??????.dat.gz,/deds-host/wcadata/INCOMING/EDW/LOGS,edw_push_processing_??????.log,FTPS,-,-
DEDS-626,MGT_BT_DSAT_DTH_Weekly_live_????????.csv,/deds-host/wcadata/INCOMING/EDW/MGT/LOGS,redw_mgt_pull_??????.log,SFTP,mgt,UKBCE-77920
DEDS-626,MGT_BT_DSAT_COM_Weekly_live_????????.csv,/deds-host/wcadata/INCOMING/EDW/MGT/LOGS,redw_mgt_pull_??????.log,SFTP,mgt,UKBCE-77920
DEDS-672,BT1???????????.DAT,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,file_copy_DEDS-672_HIPCOM-CMPS_??????.log,SFTP,gen_hipcom,BTWCE-27382
DEDS-672,BT1???????????.CAR,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,file_copy_DEDS-672_CMPS-HIPCOM_??????.log,FTP,-,BTWCE-27382
DEDS-695,trendalarms-????????????.csv,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,trend_filecopy_??????.log,FTPS,-,BTOCE-40422
DEDS-695,trendmeters-????????.csv,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,trend_filecopy_??????.log,FTPS,-,BTOCE-40422
DEDS-695,trendtemp-????????.csv,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,trend_filecopy_??????.log,FTPS,-,BTOCE-40422
DEDS-695,trendiemsstatus????????.csv,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,trend_filecopy_??????.log,FTPS,-,BTOCE-40422
DEDS-704,NTS_TRN.tar,/deds-host/wcadata/EBCSource/NTSEBC01/logs,NTS_??????.log,FTPS,-,BTWCE-11079
DEDS-704,TCP_LPR.tar,/deds-host/wcadata/EBCSource/NTSEBC01/logs,ntsfile_processing_??????.log,FTPS,-,BTWCE-11079
DEDS-704,VIC_CAPACITY.tar,/deds-host/wcadata/EBCSource/NTSEBC01/VIC/LOGS,VIC_?????.log,FTPS,-,BTWCE-11079
DEDS-704,VIC_BILLING.tar,/deds-host/wcadata/EBCSource/NTSEBC01/VIC/LOGS,VIC_?????.log,FTPS,-,BTWCE-11079
DEDS-704,NTS_TRN_???_??????.CSV.Z,/deds-host/wcadata/EBCSource/NTSEBC01/logs,NTS_??????.log,FTPS,-,BTWCE-11079
DEDS-704,TCP_LPR_???_??????.CSV.Z,/deds-host/wcadata/EBCSource/NTSEBC01/logs,ntsfile_processing_??????.log,FTPS,-,BTWCE-11079
DEDS-704,VIC_CAPACITY_???_??????_???.CSV.Z,/deds-host/wcadata/EBCSource/NTSEBC01/VIC/LOGS,VIC_?????.log,FTPS,-,BTWCE-11079
DEDS-704,VICS_Recon_*_???_??????_???.csv.Z,/deds-host/wcadata/EBCSource/NTSEBC01/VIC/LOGS,VIC_?????.log,FTPS,-,BTWCE-11079
DEDS-704,VIC_???_??????_???.CSV.Z,/deds-host/wcadata/EBCSource/NTSEBC01/VIC/LOGS,VIC_?????.log,FTPS,-,BTWCE-11079
DEDS-717,gem_?.?_energyusage_daily_??????????????.dat,/deds-host/wcadata/INCOMING/OPDM/EUSAGE/LOGS,opdm_iems_pull_??????.log,SFTP,BTOCE-41901
DEDS-717,gem_?.?_energyusage_weekly_??????????????.dat,/deds-host/wcadata/INCOMING/OPDM/EUSAGE/LOGS,opdm_iems_pull_??????.log,SFTP,BTOCE-41901
DEDS-743,MGT_BT_DSAT_DTH_Daily_live_????????.csv,/deds-host/wcadata/INCOMING/BUT/MGT/LOGS,but_mgt_pull_??????.log,SFTP,mgt,UKBCE-78626
DEDS-743,MGT_BT_DSAT_COM_Daily_live_????????.csv,/deds-host/wcadata/INCOMING/BUT/MGT/LOGS,but_mgt_pull_??????.log,SFTP,mgt,UKBCE-78626
DEDS-403,DNP_2SDEDS_MIGCANDIDATELIST_????????_?????.dat,/deds-host/wcadata/INCOMING/DNP/EMS/REQUEST/LOGS,ems_dnp_push_??????.log,FTPS,-,BTRCE-41310
DEDS-594,DNP2SDEDS_DELTAPWDCHNG_??????????????_??????.dat,/deds-host/wcadata/INCOMING/DNP/EMS/REQUEST/LOGS,ems_dnp_push_??????.log,FTPS,-,BTRCE-51014
DEDS-535,BTOP_??????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BAL-A/JV/LOGS,bal_jv_pull_??????.log,FTPS,-,UKBCE-67549
DEDS-483,CM_CEASE_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/REQUEST/LOGS,callmap_pull_??????.log,FTPS,-,BTWCE-24652
DEDS-483,CM_PROVIDE_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/REQUEST/LOGS,callmap_pull_??????.log,FTPS,-,BTWCE-24652
DEDS-483,CM_CANCEL_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/REQUEST/LOGS,callmap_pull_??????.log,FTPS,-,BTWCE-24652
DEDS-483,CM_SEARCH_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/REQUEST/LOGS,callmap_pull_??????.log,FTPS,-,BTWCE-24652
DEDS-483,CALLMAPPING_IN_??????????????.tar,/deds-host/wcadata/INCOMING/BUT/CALLMAP/REQUEST/LOGS,callmap_pull_??????.log,FTPS,-,BTWCE-24652
DEDS-483,ack_CM_PROVIDE_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,ack_CM_SEARCH_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,ack_CM_CANCEL_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,ack_CM_CEASE_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,err_CM_PROVIDE_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,err_CM_SEARCH_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,err_CM_CANCEL_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,err_CM_CEASE_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,resp_CM_SEARCH_?????????_??????????????_*.xml,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-483,CALLMAPPING_OUT_??????????????.tar,/deds-host/wcadata/INCOMING/BUT/CALLMAP/RESPONSE/LOGS,callmap_push_??????.log,FTPS,-,BTWCE-24652
DEDS-485,BPP_CC-C????????_BUG_v*_DNH_*_*_??????????????.dat.gz,/deds-host/wcadata/INCOMING/ONM/WCC/LOGS,wcc_push_??????.log,FTPS,-,BTWCE-25342
DEDS-485,BPP_WCC-?????????_BUG_v*_FUP_*_*_??????????????.dat.gz,/deds-host/wcadata/INCOMING/ONM/WCC/LOGS,wcc_push_??????.log,FTPS,-,BTWCE-25342
DEDS-485,BPP_CC-C????????_BUG_v*_DNH_Seq_Comp_??????????????.dat,/deds-host/wcadata/INCOMING/ONM/WCC/LOGS,wcc_push_??????.log,FTPS,-,BTWCE-25342
DEDS-485,BPP_WCC-?????????_BUG_v*_FUP_Seq_Comp_??????????????.dat,/deds-host/wcadata/INCOMING/ONM/WCC/LOGS,wcc_push_??????.log,FTPS,-,BTWCE-25342
DEDS-529,D???????.D?????????.DWSIP????.Z,/deds-host/wca/data/incoming/Geneva/WSIPT/LOGS,wsip_processing_??????.log,FTPS,-,BTWCE-24303
DEDS-529,R???????.R?????????.RWSIP????.Z,/deds-host/wca/data/incoming/Geneva/WSIPT/LOGS,wsip_processing_??????.log,FTPS,-,BTWCE-24303
DEDS-529,DT_WSIP_??????????????_????.tar.Z,/deds-host/wca/data/incoming/Geneva/WSIPT/LOGS,wsip_processing_??????.log,FTPS,-,BTWCE-24303
DEDS-529,TR_WSIP_??????????????_????.tar.Z,/deds-host/wca/data/incoming/Geneva/WSIPT/LOGS,wsip_processing_??????.log,FTPS,-,BTWCE-24303
DEDS-530,?????????_N???BTRH-??????????????.csv,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/REQUEST/LOGS,ipexnna_pull_??????.log,FTPS,-,BTWCE-15061
DEDS-530,?????????_BULKACT_??????????????.csv,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/REQUEST/LOGS,ipexnna_pull_??????.log,FTPS,-,BTWCE-15061
DEDS-530,IPX_IMPORT_??????????????.tar,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/REQUEST/LOGS,ipexnna_pull_??????.log,FTPS,-,BTWCE-15061
DEDS-530,IPX_IMPORT_??????????????_SUCCESS,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/REQUEST/LOGS,ipexnna_ack_??????.log,FTPS,-,BTWCE-15061
DEDS-530,IPX_IMPORT_??????????????_FAILURE,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/REQUEST/LOGS,ipexnna_ack_??????.log,FTPS,-,BTWCE-15061
DEDS-530,?????????_N???BTRH-??????????????R.csv,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/RESPONSE/LOGS,ipexnna_push_??????.log,FTPS,-,BTWCE-15061
DEDS-530,?????????_N???BTRH-??????????????A.csv,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/RESPONSE/LOGS,ipexnna_push_??????.log,FTPS,-,BTWCE-15061
DEDS-530,?????????_N???BTRH-??????????????E.csv,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/RESPONSE/LOGS,ipexnna_push_??????.log,FTPS,-,BTWCE-15061
DEDS-530,?????????_BULKACT_??????????????E.csv,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/RESPONSE/LOGS,ipexnna_push_??????.log,FTPS,-,BTWCE-15061
DEDS-530,IPX_IMPORT_KSU_??????????????.tar,/deds-host/wcadata/INCOMING/BUT/IPEXNNA/RESPONSE/LOGS,ipexnna_push_??????.log,FTPS,-,BTWCE-15061
DEDS-573,SAAS_RB_RXDISEActForMobOrd_1.00_DNH_??_??????????????.dat,/deds-host/wca/data/outgoing/SHOP/MOB/LOGS,dise_shop_pull_??????.log,SFTP,shop_dise,BTRBCE-7718
DEDS-545,EIP_EX????_RB_SIT_?.?_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_SIT_?.?_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_INS_?.?_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_INS_?.?_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_INC_?.?_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_INC_?.?_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_OLS_?.?_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_OLS_?.?_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_LCR_?.?_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_LCR_?.?_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_CCL_?.?_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_CCL_?.?_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_BTB_ASTMAIN_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_GSU_ASTMAIN_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_BTB_ASTMAIN_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_GSU_ASTMAIN_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_BTB_ASTATR_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_GSU_ASTATR_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_BTB_ASTATR_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_GSU_ASTATR_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_BTB_ASTOSC_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_GSU_ASTOSC_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_BTB_ASTOSC_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_GSU_ASTOSC_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_CA_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_EX????_RB_CA_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-545,EIP_KOG_BUS_CONTROL_FILE_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-67883
DEDS-555,??????????????AssetFeedDelta.xml,/deds-host/wcadata/INCOMING/CMPS/JV/LOGS,cmps_jv_pull_??????.log,FTPS,-,BTRBCE-12715
DEDS-516,NI_RC_emailData_*_*_??????????????.csv.gz,/deds-host/wcadata/INCOMING/EDW/AVB/LOGS,edw_avbrowne_pull_??????.log,FTPS,-,BTRCE-36321
DEDS-306,D???????.D?????????.DHCC????.Z,/deds-host/wcadata/INCOMING/ONM/HCC/LOGS,onm_hcc_processing_??????.log,FTPS,-,BTWCE-19755
DEDS-306,M???????.M?????????.MHCC????.Z,/deds-host/wcadata/INCOMING/ONM/HCC/LOGS,onm_hcc_processing_??????.log,FTPS,-,BTWCE-19755
DEDS-306,DT_HCC_??????????????_????.tar.Z,/deds-host/wcadata/INCOMING/ONM/HCC/LOGS,onm_hcc_processing_??????.log,FTPS,-,BTWCE-19755
DEDS-306,M_HCC_??????????????_????.tar.Z,/deds-host/wcadata/INCOMING/ONM/HCC/LOGS,onm_hcc_processing_??????.log,FTPS,-,BTWCE-19755
DEDS-580,???_*_*_v*_*_*_*_??????????????.dat.gz,/deds-host/wcadata/INCOMING/GIB/JV/LOGS,gib_jv_push_??????.log,FTPS,-,UKBCE-71740
DEDS-580,CONSULATE_ACCOUNT_??????????????.tar,/deds-host/wcadata/INCOMING/GIB/JV/LOGS,gib_jv_push_??????.log,FTPS,-,UKBCE-71740
DEDS-580,???_*_*_v*_*_Seq_Comp_??????????????.dat.gz,/deds-host/wcadata/INCOMING/GIB/JV/LOGS,gib_jv_push_??????.log,FTPS,-,UKBCE-71740
DEDS-649,??????????????AssetFeedDelta.xml,/deds-host/wcadata/INCOMING/UKBNC/JV/LOGS,jv_ukbnc_xfb_??????.log,FTPS,-,BTRCE-15026
DEDS-505,CPEMAIL_EDW_2SDEDS_DIMILESTONE_????????_??_??.dat.gz,/deds-host/wcadata/INCOMING/EDW/DIPULL/LOGS,edw_di_pull_??????.log,FTPS,-,BTRCE-45399
DEDS-578,EIP_EX????_??????????????.tar,/deds-host/wcadata/INCOMING/EIPAL/SAMKNOWS/LOGS,eipal_sam_push_??????.log,FTPS,-,BTRCE-50108
DEDS-578,EIP_EX????_RABB_NCS_?.?_DNH_?_?_??????????????.dat.Z.pgp,/deds-host/wcadata/INCOMING/EIPAL/SAMKNOWS/LOGS,eipal_sam_push_??????.log,FTPS,-,BTRCE-50108
DEDS-579,PROF_CHNG_REP_DLY_?????????_??_??????????????.xml.Z,/deds-host/wcadata/INCOMING/EDW/BIPASSET/LOGS,edw_bip_pull_??????.log,FTPS,-,BTRCE-50108
DEDS-579,PERF_CHNG_REP_DLY_?????????_??_??????????????.xml.Z,/deds-host/wcadata/INCOMING/EDW/BIPASSET/LOGS,edw_bip_pull_??????.log,FTPS,-,BTRCE-50108
DEDS-579,ALR_WCOM_?????????_??_??????????????.csv.Z,/deds-host/wcadata/INCOMING/EDW/BIPASSET/LOGS,edw_bip_pull_??????.log,FTPS,-,BTRCE-50108
DEDS-579,ALR_W_?????????_??_??????????????.csv.Z,/deds-host/wcadata/INCOMING/EDW/BIPASSET/LOGS,edw_bip_pull_??????.log,FTPS,-,BTRCE-50108
DEDS-579,ALR_MCOM_?????????_??_??????????????.csv.Z,/deds-host/wcadata/INCOMING/EDW/BIPASSET/LOGS,edw_bip_pull_??????.log,FTPS,-,BTRCE-50108
DEDS-579,ALR_M_?????????_??_??????????????.csv.Z,/deds-host/wcadata/INCOMING/EDW/BIPASSET/LOGS,edw_bip_pull_??????.log,FTPS,-,BTRCE-50108
DEDS-591,CPEMAIL_DNP_2SDEDS_CMPRMISEDEML_????????????_*_*.dat.gz,/deds-host/wcadata/INCOMING/DNP/ECP/LOGS,ecp_dnp_pull_??????.log,FTPS,-,BTRCE-50729
DEDS-591,CPEMAIL_DNP_2SDEDS_EMAILACCESSDATE_????????_*_*.dat.gz,/deds-host/wcadata/INCOMING/DNP/ECP/LOGS,ecp_dnp_pull_??????.log,FTPS,-,BTRCE-50729
DEDS-627,MGT_BT_DSAT_DTH_Daily_int_????????.csv,/deds-host/wcadata/INCOMING/BUT/MGT/LOGS,but_mgt_pull_??????.log,SFTP,mgt,BTRCE-51045
DEDS-627,MGT_BT_DSAT_COM_Daily_int_????????.csv,/deds-host/wcadata/INCOMING/BUT/MGT/LOGS,but_mgt_pull_??????.log,SFTP,mgt,BTRCE-51045
DEDS-526,CRMUPDATE_????????.tgz,/deds-host/wcadata/INCOMING/CSEARCH/CRM/LOGS,csearch_qad_pull_??????.log,FTPS,-,BTRECE-4951
DEDS-701,Onebillcbfile??????????????.csv,/deds-host/wcadata/INCOMING/BAL-A/DISCUS/LOGS,discus_bala_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Onebilltrmfile??????????????.csv,/deds-host/wcadata/INCOMING/BAL-A/DISCUS/LOGS,discus_bala_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Onebilltxtfile??????????????.csv,/deds-host/wcadata/INCOMING/BAL-A/DISCUS/LOGS,discus_bala_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Onebillocubfile??????????????.csv,/deds-host/wcadata/INCOMING/BAL-A/DISCUS/LOGS,discus_bala_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Onebillfcubfile??????????????.csv,/deds-host/wcadata/INCOMING/BAL-A/DISCUS/LOGS,discus_bala_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Onebillocbfile??????????????.csv,/deds-host/wcadata/INCOMING/BAL-A/DISCUS/LOGS,discus_bala_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Onebillcbfile??????????????.csv,/deds-host/wca/data/outgoing/DISCUS/ONEBILL/LOGS,discus_onebill_push_????????.log,SFTP,push_dise,BTRBCE-9634
DEDS-701,Onebilltrmfile??????????????.csv,/deds-host/wca/data/outgoing/DISCUS/ONEBILL/LOGS,discus_onebill_push_????????.log,SFTP,push_dise,BTRBCE-9634
DEDS-701,Onebilltxtfile??????????????.csv,/deds-host/wca/data/outgoing/DISCUS/ONEBILL/LOGS,discus_onebill_push_????????.log,SFTP,push_dise,BTRBCE-9634
DEDS-701,DISE????????Addr.csv,/deds-host/wca/data/outgoing/DISCUS/ACCOUNT/LOGS,discus_account_push_????????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,DISE????????Debt.csv,/deds-host/wca/data/outgoing/DISCUS/ACCOUNT/LOGS,discus_account_push_????????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,AccountListing_??????.csv,/deds-host/wca/data/outgoing/DISCUS/ACCOUNT/LOGS,discus_account_push_????????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,IOTAB?????_????????.CSV,/deds-host/wca/data/outgoing/IOTA/REVENUE/LOGS,dise_iota_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,IOTAU?????_????????.CSV,/deds-host/wca/data/outgoing/IOTA/REVENUE/LOGS,dise_iota_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,emergservi.gz,/deds-host/wca/data/outgoing/ODM/EMERG/LOGS,dise_odm_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,ANALYSER_SDEDS.tar,/deds-host/wca/data/outgoing/CFB/INVOICE/LOGS,dise_cfb_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,SERVICES.gz,/deds-host/wca/data/outgoing/CMF/ASSET/LOGS,dise_cmf_asset_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,TARIFFS.gz,/deds-host/wca/data/outgoing/CMF/ASSET/LOGS,dise_cmf_asset_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,SERVICES.csv,/deds-host/wca/data/outgoing/CMF/ASSET/LOGS,dise_cmf_asset_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,TARIFFS.csv,/deds-host/wca/data/outgoing/CMF/ASSET/LOGS,dise_cmf_asset_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,DISE3G_CustomerBase_??_??_????.csv.gz,/deds-host/wca/data/outgoing/CMF/DISE3G/LOGS,dise_cmf_dise3g_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,mobspend????????,/deds-host/wca/data/incoming/ADDER/BOWLINE/OUT/LOGS,adr_mob_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,DISE3G_CustomerBase_??_??_????.csv.gz,/deds-host/wca/data/incoming/ADDER/DISE3G/LOGS,adr_d3g_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,BTM_??????????????.*,/deds-host/wca/data/outgoing/MDCR/BTM/LOGS,mdcr_filepush_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Corporate*_*.csv.gz,/deds-host/wca/data/CP/RYDER/AUTOBALANCE/LOGS,dise_ryd_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Account*_*.csv.gz,/deds-host/wca/data/CP/RYDER/AUTOBALANCE/LOGS,dise_ryd_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,Group*_*.csv.gz,/deds-host/wca/data/CP/RYDER/AUTOBALANCE/LOGS,dise_ryd_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,VOD_CD.??????,/deds-host/wca/data/outgoing/GDW/VOD/LOGS,dise_gdw_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,VOD_ID.??????,/deds-host/wca/data/outgoing/GDW/VOD/LOGS,dise_gdw_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,vod_cd.??????,/deds-host/wca/data/outgoing/GDW/VOD/LOGS,dise_gdw_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-701,vod_id.??????,/deds-host/wca/data/outgoing/GDW/VOD/LOGS,dise_gdw_push_??????.log,SFTP,pull_dise,BTRBCE-9634
DEDS-588,MulticastData_M_v*.?_1_1_??????????????_?????????.dat.zip,/deds-host/wcadata/INCOMING/UII/TVC/LOGS,uii_tvc_push_??????.log,FTPS,-,21CNCE-54987
DEDS-588,MulticastData_W_v*.?_1_1_??????????????_?????????.dat.zip,/deds-host/wcadata/INCOMING/UII/TVC/LOGS,uii_tvc_push_??????.log,FTPS,-,21CNCE-54987
DEDS-588,MulticastData_M_v*.?_1_1_??????????????_?????????.dat,/deds-host/wcadata/INCOMING/UII/TVC/LOGS,uii_tvc_push_??????.log,FTPS,-,21CNCE-54987   
DEDS-588,MulticastData_W_v*.?_1_1_??????????????_?????????.dat,/deds-host/wcadata/INCOMING/UII/TVC/LOGS,uii_tvc_push_??????.log,FTPS,-,21CNCE-54987
DEDS-666,EIP_EX????_GSU_PRDATR_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDATR_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDATR_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDATR_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDPP_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDPP_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDPP_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDPP_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDPRL_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDPRL_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDPRL_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDPRL_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDPRMAP_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDPRMAP_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDPRMAP_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDPRMAP_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_RB_RABPM_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_RB_RABPM_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDMAIN_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDMAIN_?.??_MNH_*_*_????????.dat.gz,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_GSU_PRDMAIN_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-666,EIP_EX????_BTB_PRDMAIN_?.??_MNH_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-75124
DEDS-715,Nexidia_????????.csv,/deds-host/wca/data/INTERFACES/CDDE/NEXIDIA/LOGS,cdde_nex_push_??????.log,SFTP,nexidia,BTRCE-52946
DEDS-715,VMM_EX????-?_?_DNH_?_?_??????????????_?.dat.gz,/deds-host/wca/data/INTERFACES/EDW/NEXIDIA/LOGS,edw_nex_push_??????.log,SFTP,nexidia,BTRCE-52946
DEDS-715,VMM_EX????-?_?_DNH_*_??????????????_?.zip,/deds-host/wca/data/INTERFACES/NEX_EXTR/NEXIDIA/LOGS,nextr_nex_push_??????.log,SFTP,nexidia,BTRCE-52946
DEDS-727,BTYAHOO_MAILBOX_DETAIL_??????????????_??_??.csv,/deds-host/wcadata/INCOMING/EDW/YAHOO/LOGS,edw_yahoo_pull_??????.log,FTPS,-,BTRCE-45923
DEDS-727,BTYAHOO_MAILBOX_DETAIL_??????????????_??_??.csv,/deds-host/wcadata/INCOMING/CISP/YAHOO/LOGS,cisp_yahoo_pull_??????.log,FTPS,-,BTRCE-45923
DEDS-654,order_item_????????_??.csv.gz,/deds-host/wcadata/INCOMING/BUT/WLMS/LOGS,logica_processing_??????.log,FTPS,-,BTWCE-28295
DEDS-654,order_item_detail_????????_??.csv.gz,/deds-host/wcadata/INCOMING/BUT/WLMS/LOGS,logica_processing_??????.log,FTPS,-,BTWCE-28295
DEDS-694,WCLI_OUT_??????????????.tar,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcack_Out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcack_Out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcack_out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcack_out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wchsk_Out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wchsk_Out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wchsk_out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wchsk_out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcack_Out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcack_Out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcack_out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcack_out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wchsk_Out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wchsk_Out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wchsk_out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wchsk_out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcack_Out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcack_Out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcack_out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcack_out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wchsk_Out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wchsk_Out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wchsk_out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wchsk_out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcerr_Out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcerr_out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcerr_Out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcerr_out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcerr_Out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_Wcerr_out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcerr_Out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcerr_out_a.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcerr_Out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcerr_out_b.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcerr_Out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,20??????_????_?????????_wcerr_out_c.xml,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPUSH,WCLI_push_??????.log,FTPS,-,-
DEDS-694,WCLI_IN_??????????????.tar,/deds-host/wcadata/INCOMING/BUT/WCLI/WCLIPULL/LOGS,WCLI_pull_??????.log,FTPS,-,-
DEDS-738,BT1???????????.DAT,/deds-host/wcadata/INCOMING/BUT/IPVS/CAR/LOGS,ipvs_eff_pull_??????.log,SFTP,gen_hipcom,BTWCE-30855
DEDS-738,BT1???????????.DAT,/deds-host/wcadata/INCOMING/BUT/IPVS/EFF/LOGS,eff_ipvs_push_??????.log,SFTP,gen_hipcom,BTWCE-30855
DEDS-753,data.txt,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,file_move_DEDS-753_ESB-SWISSCOM_??????.log,FTP,-,GSCE-107890
DEDS-753,dwahl.txt,/deds-host/olos/VDC/GEN_SCRIPTS/FILECOPY/LOGS,file_move_DEDS-753_ESB-SWISSCOM_??????.log,FTP,-,GSCE-107890
DEDS-754,BT_EXPERIAN_CREDIT_REF_DATA_??????_???.dat.gz,/deds-host/wcadata/INCOMING/EDW/EXPERIAN/LOGS,edw_experian_pull_??????.log,FTPS,-,BTRBCE-14656
DEDS-754,BT_EXPERIAN_CREDIT_REF_DATA_??????.ctrl,/deds-host/wcadata/INCOMING/EDW/EXPERIAN/LOGS,edw_experian_pull_??????.log,FTPS,-,BTRBCE-14656
DEDS-784,M_WSIP_??????????????_????.tar.Z,/deds-host/wcadata/INCOMING/EDW/EXPERIAN/LOGS,edw_experian_pull_??????.log,FTPS,-,BTWCE-32337
DEDS-784,M???????.M?????????.MWSIP????.Z,/deds-host/wcadata/INCOMING/EDW/EXPERIAN/LOGS,edw_experian_pull_??????.log,FTPS,-,BTWCE-32337
DEDS-628,?????????.YPSDIR.DAT,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_licensee_??????.log,FTPS,-,BTWCE-28562
DEDS-628,?????????.*stdah.dat,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_licensee_??????.log,FTPS,-,BTWCE-28562
DEDS-854,BT?????*.AUD,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_cp_??????.log,FTPS,-,BTRECE-5276
DEDS-854,BT???????*.csv,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_cp_??????.log,FTPS,-,BTRECE-5276
DEDS-854,BT???????*.AUD,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_cp_??????.log,FTPS,-,BTRECE-5276
DEDS-854,BT???????*csv,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_cp_??????.log,FTPS,-,BTRECE-5276
DEDS-842,Qbase_RVdata_????????.zip,/deds-host/wca/data/INTERFACES/MARC/QBASE/LOGS,file_move_DEDS-842_QBASE-MARC_??????.log,FTPS,-,BTRBCE-16558
DEDS-864,TOTP_SOR_BEMD-GRPS_V?_MNH_?_?_??????????????.dat,/deds-host/wca/data/INTERFACES/PMS/OUT/LOGS,pms_kiwi_push_??????.log,FTPS,-,BTOCE-45669
DEDS-864,TOTP_SOR_BEMD-GNS_V?_MNH_?_?_??????????????.dat,/deds-host/wca/data/INTERFACES/PMS/OUT/LOGS,pms_kiwi_push_??????.log,FTPS,-,BTOCE-45669
DEDS-864,TOTP_SOR_BEMD-NA_V?_MNH_?_?_??????????????.dat,/deds-host/wca/data/INTERFACES/PMS/IN/LOGS,pms_kiwi_push_??????.log,FTPS,-,BTOCE-45669
DEDS-864,TOTP_SOR_BEMD-FG_V?_MNH_?_?_??????????????.dat,/deds-host/wca/data/INTERFACES/PMS/IN/LOGS,pms_kiwi_push_??????.log,FTPS,-,BTOCE-45669
DEDS-804,ESDBAddress????????,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_ADDR/LOGS,wsipt_eu_pull_??????.log,FTPS,-,BTWCE-29475
DEDS-804,EU_REQ_??????????????.tar,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_ADDR/LOGS,wsipt_eu_pull_??????.log,FTPS,-,BTWCE-29475
DEDS-804,EU_REQ_??????????????_SUCCESS,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_ADDR/LOGS,wsipt_eu_ack_??????.log,FTPS,-,BTWCE-29475
DEDS-804,EU_REQ_??????????????_FAILURE,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_ADDR/LOGS,wsipt_eu_ack_??????.log,FTPS,-,BTWCE-29475
DEDS-804,EU_RES_??????????????.tar,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_RESPONSE/LOGS,wsipt_eu_pull_??????.log,FTPS,-,BTWCE-29475
DEDS-804,ESDBSuccess????????_?????????????,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_RESPONSE/LOGS,wsipt_eu_push.log,FTPS,-,BTWCE-29475
DEDS-804,ESDBFailure????????_?????????????,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_RESPONSE/LOGS,wsipt_eu_push.log,FTPS,-,BTWCE-29475
DEDS-804,ESDBUnprocessed????????_?????????????,/deds-host/wca/data/INTERFACES/BUT/WSIPT/EU_RESPONSE/LOGS,wsipt_eu_push.log,FTPS,-,BTWCE-29475
DEDS-813,?????????ESDBAUDIT_??????????????.csv,/deds-host/wca/data/INTERFACES/BUT/IPEX/EU_REQUEST/LOGS,ipex_eu_pull_??????.log,FTPS,-,BTWCE-30101
DEDS-813,?????????ESDBAUDIT_??????????????.CSV,/deds-host/wca/data/INTERFACES/BUT/IPEX/EU_REQUEST/LOGS,ipex_eu_pull_??????.log,FTPS,-,BTWCE-30101
DEDS-813,IPEXEU_REQ_??????????????_SUCCESS,/deds-host/wca/data/INTERFACES/BUT/IPEX/EU_REQUEST/LOGS,ipex_eu_pull_??????.log,FTPS,-,BTWCE-30101
DEDS-813,IPEXEU_REQ_??????????????_FAILURE,/deds-host/wca/data/INTERFACES/BUT/IPEX/EU_REQUEST/LOGS,ipex_eu_pull_??????.log,FTPS,-,BTWCE-30101
DEDS-813,IPEXEU_REQ_??????????????.tar,/deds-host/wca/data/INTERFACES/BUT/IPEX/EU_REQUEST/LOGS,ipex_eu_pull_??????.log,FTPS,-,BTWCE-30101
DEDS-813,?????????ESDBAUDIT_??????????????_Response*.csv,/deds-host/wca/data/INTERFACES/BUT/IPEX/EU_RESPONSE/LOGS,ipex_eu_push_??????.log,FTPS,-,BTWCE-30101
DEDS-813,?????????ESDBAUDIT_??????????????_Response*.CSV,/deds-host/wca/data/INTERFACES/BUT/IPEX/EU_RESPONSE/LOGS,ipex_eu_push_??????.log,FTPS,-,BTWCE-30101
DEDS-831,RAMBo_sync_events_????????_*_*.csv.gz,/deds-host/wca/data/INTERFACES/RAMBO/RCD/LOGS,rcd_rambo_pull_??????.log,FTPS,-,BTWCE-29982
DEDS-831,RAMBo_sync_events_recovered_????????_*_*.csv.gz,/deds-host/wca/data/INTERFACES/RAMBO/RCD/LOGS,rcd_rambo_pull_??????.log,FTPS,-,BTWCE-29982
DEDS-900,RBM_rated_CDRs_????????_????????.dat.gz,/deds-host/wca/data/incoming/UR/RAFEED/LOGS,trap_logica_pull_??????.log,FTPS,-,-
DEDS-900,RBM_Rejected_CDRs_????????_????????.dat.gz,/deds-host/wca/data/incoming/UR/RAFEED/LOGS,trap_logica_pull_??????.log,FTPS,-,-
DEDS-783,BUT_SK_??????????????.tar,/deds-host/wcadata/INCOMING/BUT/SESSIONKILL/SESSIONPULL/LOGS,but_sk_pull_??????.log,FTPS,-,BTRCE-60384
DEDS-783,OP_BUT_KillSession_*_?????????.csv,/deds-host/wcadata/INCOMING/BUT/SESSIONKILL/SESSIONPULL/LOGS,but_sk_pull_??????.log,FTPS,-,BTRCE-60384
DEDS-783,OP_BUT_KillSession_Result_*_?????????.tar,/deds-host/wcadata/INCOMING/BUT/SESSIONKILL/SESSIONPUSH/LOGS,sk_response_??????.log,FTPS,-,BTRCE-60384
DEDS-894,NOTIFY_TAKEOVERS.csv,/deds-host/wcadata/INCOMING/MCSO/CPS_ROBO/LOGS,mcso_cpsrobo_pull_??????.log,FTP,-,-
DEDS-894,U??????S.???,/deds-host/wcadata/INCOMING/MCSO/CPS_ROBO/LOGS,mcso_cpsrobo_pull_??????.log,FTP,-,-
DEDS-832,operator_*_user_report_????-??-??.csv,/deds-host/wcadata/INCOMING/EDW/FSECURE/LOGS,edw_fsecure_pull_??????.log,FTPS,-,BTRCE-64210
DEDS-655,telereal_jobs.data,/deds-host/wcadata/INCOMING/PAL/TELEREAL/REQUEST/LOGS,tel_pal_xfb_??????.log,-,-,BTGCE-789 
DEDS-655,skyline_exchange_data.csv,/deds-host/wcadata/INCOMING/PAL/TELEREAL/REQUEST/LOGS,tel_pal_xfb_??????.log,-,-,BTGCE-789 
DEDS-655,CDTCORD.MVS.*.SKYLINE.DATA,/deds-host/wcadata/INCOMING/PAL/TELEREAL/REQUEST/LOGS,tel_pal_xfb_??????.log,-,-,BTGCE-789 
DEDS-655,telereal_pfc.csv,/deds-host/wcadata/INCOMING/PAL/TELEREAL/RESPONSE/LOGS,pal_tel_push_??????.log,-,-,BTGCE-789 
DEDS-655,telereal_odc.csv,/deds-host/wcadata/INCOMING/PAL/TELEREAL/RESPONSE/LOGS,pal_tel_push_??????.log,-,-,BTGCE-789 
DEDS-93,TCP_LPR.tar,/deds-host/wcadata/EBCSource/NTSEBC01/logs,ntsfile_processing_??????.log,FTPS,-,-
DEDS-93,TCP_LPR_???_??????.csv.Z,/deds-host/wcadata/EBCSource/NTSEBC01/logs,ntsfile_processing_??????.log,FTPS,-,-
DEDS-170,NOTIFY_TAKEOVERS.csv,/deds-host/wcadata/INCOMING/EDW/WINBACK/LOGS,redw_cpsrobo_pull_??????.log,FTPS,-,BTRCE-25174
DEDS-170,U??????S.???,/deds-host/wcadata/INCOMING/EDW/WINBACK/LOGS,redw_cpsrobo_pull_??????.log,FTPS,-,BTRCE-25174
DEDS-216,EIP_??????_LBI_*_????????.dat,/deds-host/wcadata/INCOMING/EDW/LBI/LOGS,edw_lbi_pull_??????.log,FTPS,-,BTRCE-26726
DEDS-174,?????????-*.csv,/deds-host/wca/data/incoming/MUI/PHARAOH/LOGS,mui_push_??????.log,FTPS,-,BTOCE-20549
DEDS-439,bi_export_export_subscriptions_used.csv,/deds-host/wcadata/INCOMING/EDW/FSECURE/LOGS,edw_fsecure_pull_??????.log,FTPS,-,BTRCE-39187
DEDS-460,theTrainline_????????.zip,/deds-host/wca/data/incoming/CDDE/TRAINLINE/LOGS,cdde_trainline_push_??????.log,FTPS,-,BTGCE-3654
DEDS-527,TrainlineBTDailyFile????????.csv,/deds-host/wcadata/INCOMING/PAL/TRAINLINE/LOGS,trainline_pal_pull_??????.log,FTPS,-,BTGCE-3654
DEDS-354,SAAS_RB_RXDISEActForMobOrd_1.00_DNH_??_??????????????.dat,/deds-host/wca/data/outgoing/SHOP/MOB/LOGS,dise_shop_pull_??????.log,SFTP,shop_dise,BTRBCE-5986
DEDS-153,?????????_WLR3PSTN_????????_?of?.csv.gz,/deds-host/wca/data/incoming/MIS/BTRetailPull/LOGS,bip_retail_pull_??????.log,FTPS,-,-
DEDS-153,?????????_WLR3PSTN_Filtered_????????_?of?.csv.gz,/deds-host/wca/data/incoming/MIS/BTRetailPush/LOGS,bip_retail_push_??????.log,FTPS,-,-
DEDS-434,EMP_VUS_BDTD_*_MNH_*_??????????????.dat.gz,/deds-host/wcadata/INCOMING/BAL-A/GREATPLAINS/LOGS,greatplains_bala_push_??????.log,FTPS,-,BTRBCE-6212
DEDS-434,EMP_VUK_BDTD_*_MNH_*_??????????????.dat.gz,/deds-host/wcadata/INCOMING/BAL-A/GREATPLAINS/LOGS,greatplains_bala_push_??????.log,FTPS,-,BTRBCE-6212
DEDS-434,EMP_BIC_BDTD_*_MNH_*_??????????????.dat.gz,/deds-host/wcadata/INCOMING/BAL-A/GREATPLAINS/LOGS,greatplains_bala_push_??????.log,FTPS,-,BTRBCE-6212
DEDS-301,?????????_LLUMPF_????????_?f??.csv.gz,/deds-host/wca/data/incoming/ORBIT/LLU/LOGS,orbit_LLU_processing_??????.log,FTPS,-,ORCE-29847
DEDS-301,?????????_LLUMPF_????????_??f??.csv.gz,/deds-host/wca/data/incoming/ORBIT/LLU/LOGS,orbit_LLU_processing_??????.log,FTPS,-,ORCE-29847
DEDS-401,ESERVEUNBL*.gz,/deds-host/wcadata/INCOMING/BAL-A/DISEFILES/LOGS,bal_dise_pull_??????.log,SFTP,dise,BTRBCE-9590
DEDS-401,ESERVEBUND*.gz,/deds-host/wcadata/INCOMING/BAL-A/DISEFILES/LOGS,bal_dise_pull_??????.log,SFTP,dise,BTRBCE-9590
DEDS-463,BTNESTHRINT????????_*_*.csv,/deds-host/wca/data/outgoing/PEOPLESOFT/NEST/OUT/LOGS,pps_push_??????.log,SFTP,BTGCE-3823
DEDS-463,BTNESTDEHRINT????????_*_*.csv,/deds-host/wca/data/outgoing/PEOPLESOFT/NEST/OUT/LOGS,pps_push_??????.log,SFTP,BTGCE-3823
DEDS-463,NESTContributions.csv,/deds-host/wca/data/outgoing/PAYROLL/NEST/OUT/LOGS,pay_push_??????.log,SFTP,BTGCE-3823
DEDS-114,BPP_WCC-?????????_BUG_v?_FUP_?_?_??????????????.dat.gz,/deds-host/wcadata/INCOMING/BAL-A/LOGS,ContentConnectLogs_??????.log,FTPS,-,-
DEDS-114,BPP_WCC-?????????_BUG_v?_FUP_Seq_Comp_??????????????.dat,/deds-host/wcadata/INCOMING/BAL-A/LOGS,ContentConnectLogs_??????.log,FTPS,-,-
DEDS-112,order_item_????????_??.csv.gz,/deds-host/wcadata/INCOMING/BUT/WLMS/LOGS,logica_processing_??????.log,FTPS,-,BTWCE-10298
DEDS-112,order_item_detail_????????_??.csv.gz,/deds-host/wcadata/INCOMING/BUT/WLMS/LOGS,logica_processing_??????.log,FTPS,-,BTWCE-10298
DEDS-112,inventory_item_????????_??.csv.gz,/deds-host/wcadata/INCOMING/BUT/WLMS/LOGS,logica_processing_??????.log.FTPS,BTWCE-10298
DEDS-112,inventory_item_detail_????????_??.csv.gz,/deds-host/wcadata/INCOMING/BUT/WLMS/LOGS,logica_processing_??????.log,FTPS,-,BTWCE-10298
DEDS-236,bp_export????????.xls.asc,/deds-host/wcadata/INCOMING/PAL/ISOS/LOGS,pal_isos_??????.log,SFTP,isos,BTGCE-1899
DEDS-274,BPP_CC-C????????_BUG_v?_DNH_?_?_??????????????.dat.gz,/deds-host/wcadata/FUSION/INCOMING/RAWLOG/LOGS,ContentConnectLogs_??????.log,FTPS,-,21CNCE-45875
DEDS-274,BPP_CC-C????????_BUG_v?_DNH_Seq_Comp_??????????????.dat,/deds-host/wcadata/FUSION/INCOMING/RAWLOG/LOGS,ContentConnectLogs_??????.log,FTPS,-,21CNCE-45875
DEDS-271,Harlequins_ivr_data_feed_????????.csv,/deds-host/wca/data/outgoing/HARRIER/ISPCO/LOGS,tribe_harrier_push_??????.log,SFTP,tribe,BTWCE-18360
DEDS-244,??????????-*-216905785-??????????????.dat,/deds-host/wca/data/incoming/Geneva/GBBU/LOGS,genius_bbu_??????.log,FTPS,-,BTWCE-19827
DEDS-248,HML_OHS_????????.xml,/deds-host/wca/data/incoming/CDDE/HML/LOGS,cdde_hml_??????.log,FTPS,-,BTGCE-3037
DEDS-224,mig_order_item_????????_*.csv.gz,/deds-host/wcadata/INCOMING/BUT/HQMIGRATION/LOGS,but_hqmig_pull_??????.log,FTPS,-,BTWCE-18236
DEDS-224,mig_order_item_detail_????????_*.csv.gz,/deds-host/wcadata/INCOMING/BUT/HQMIGRATION/LOGS,but_hqmig_pull_??????.log,FTPS,-,BTWCE-18236
DEDS-257,TSG_????????.csv,/deds-host/wcadata/INCOMING/BUT/TSG/LOGS,but_tsg_pull_??????.log,FTPS,-,BTRCE-26562
DEDS-239,??????????_CUSTOMER_CREATE_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_CUSTOMER_MODIFY_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_CUSTOMER_DELETE_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_SITE_CREATE_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_SITE_MODIFY_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_SITE_DELETE_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_USER_CREATE_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_USER_MODIFY_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-239,??????????_USER_DELETE_???????_????????????.XML,/deds-host/wcadata/INCOMING/R1OSS/IPVS,r1oss_hipcom_??????.log,SFTP,r1oss,BTRBCE-8518
DEDS-210,PROF_CHNG_REP_DLY_?????????_*_??????????????.xml.Z,/deds-host/wca/data/incoming/MIS/DataProfile/LOGS,dfprocessing_??????.log,FTPS,-,BTRCE-25032
DEDS-210,PERF_CHNG_REP_DLY_?????????_*_??????????????.xml.Z,/deds-host/wca/data/incoming/MIS/DataProfile/LOGS,dfprocessing_??????.log,FTPS,-,BTRCE-25032
DEDS-238,D???????.D?????????.DIPVS????.Z,/deds-host/wcadata/OUTGOING/RETAILONM/IPVS/LOGS,ronm_pull_??????.log,-,-,BTRBCE-8518
DEDS-238,RONM_IPVS_??????????????.tar,/deds-host/wcadata/OUTGOING/RETAILONM/IPVS/LOGS,ronm_pull_??????.log,-,-,BTRBCE-8518   
DEDS-343,JDC_New_Cust_??????.csv.gz,/deds-host/wcadata/INCOMING/EDW/DISE/LOGS,dise_edw_pull_??????.log,SFTP,javelin,BTRBCE-5570
DEDS-343,JDC_Current??????.csv.gz,/deds-host/wcadata/INCOMING/EDW/DISE/LOGS,dise_edw_pull_??????.log,SFTP,javelin,BTRBCE-5570
DEDS-333,MME01-?????????-????????.csv,/deds-host/wcadata/OUTGOING/GONM/MDMMME/LOGS,gonm_mdmmme_pull_??????.log,FTPS,-,BTGSCE-82890
DEDS-463,BTNESTDEHRINT????????_*_*.csv,/deds-host/wca/data/outgoing/PEOPLESOFT/NEST/OUT/LOGS,pps_push_??????.log,-,BTGCE-3823
DEDS-463,BTNESTHRINT????????_*_*.csv,/deds-host/wca/data/outgoing/PEOPLESOFT/NEST/OUT/LOGS,pps_push_??????.log,-,BTGCE-3823
DEDS-370,EIP_EX????_RB_PUG_?.?_DNH_*_*_????????.dat.Z,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-11279
DEDS-370,EIP_EX????_RB_PUG_?.?_DNH_*_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-11279
DEDS-370,EIP_EX????_RB_BAC_?.?_MNH_*_*_????????.dat.Z,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-11279
DEDS-370,EIP_EX????_RB_BAC_?.?_MNH_*_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-11279
DEDS-370,EIP_EX????_RB_SH_?.?_MNH_*_*_????????.dat.Z,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-11279
DEDS-370,EIP_EX????_RB_SH_?.?_MNH_*_*_????????.ctl,/deds-host/wca/data/incoming/UR/KOGNITIO/LOGS,ur_kognitio_push_??????.log,FTPS,-,UKBCE-11279
DEDS-525,BTGS_APAC_CUSTOMER_MASTER_????????????.csv.gz,/deds-host/wcadata/INCOMING/PAL/AKRITIV/LOGS,pal_akritiv_push_??????.log,SFTP,akritiv,BTGSCE-92729
DEDS-525,BTGS_APAC_AR_OPEN_ITEMS_????????????.csv.gz,/deds-host/wcadata/INCOMING/PAL/AKRITIV/LOGS,pal_akritiv_push_??????.log,SFTP,akritiv,BTGSCE-92729
DEDS-502,DNP_2SDEDS_COMPROMISEDEMAILS_????????_???.dat,/deds-host/wcadata/INCOMING/DNP/ECMP/LOGS,ecmp_dnp_pull_??????.log,FTPS,-,BTRCE-44813
DEDS-502,DNP_2SDEDS_EMAILDETAILS_????????_???.dat,/deds-host/wcadata/INCOMING/DNP/EUSL/LOGS,eusl_dnp_pull_??????.log,FTPS,-,BTRCE-44813
NA,WLR3_AssetReportLog_??????.csv,/deds-host/wca/data/incoming/ORBIT/LOGS,orbit_reportgen_??????.log,FTP
NA,FVA_AssetReportLog_????????.csv,/deds-host/wca/data/incoming/ORBIT/LOGS,orbit_reportgen_??????.log,FTP
NA,LLU_AssetReportLog_??????.csv,/deds-host/wca/data/incoming/ORBIT/LOGS,orbit_reportgen_??????.log,FTP
NA,B0_mdn_subscriber_????????,/deds-host/wcadata/INCOMING/BAL-A/LOGS,bal_to_vodafone_????????.log,-,-,
NA,B0_mdn_advice_??????????,/deds-host/wcadata/INCOMING/BAL-A/LOGS,bal_to_vodafone_????????.log,SFTP,vodafone,
DEDS-572,
DEDS-158,T7D446*,/deds-host/wcadata/INCOMING/ONM/ONMOMP_OLOS/LOGS,onm_omp_processing_??????.log,FTPS,-,VOICECE-1707
DEDS-158,T7D335*,/deds-host/wcadata/INCOMING/ONM/ONMOMP_OLOS/LOGS,onm_omp_processing_??????.log,FTPS,-,VOICECE-1707
DEDS-166,?????????.bulkFTTCDNs.????????.csv,/deds-host/wca/data/incoming/SMC/LOGS,completedresponse_processing_??????.log,FTP,-BTORCE-5461
DEDS-166,?????????.bulkLLUDNs.????????.csv,/deds-host/wca/data/incoming/SMC/LOGS,completedresponse_processing_??????.log,FTP,-,BTORCE-5461
DEDS-166,?????????.bulkFTTPDNs.????????.csv,/deds-host/wca/data/incoming/SMC/LOGS,completedresponse_processing_??????.log,FTP,-BTORCE-5461
DEDS-166,?????????.bulkFTTCDNs.????????.csv,/deds-host/wca/data/incoming/SMC/LOGS,newrequest_processing_??????.log,FTP,-,BTORCE-5461
DEDS-166,?????????.bulkLLUDNs.????????.csv,/deds-host/wca/data/incoming/SMC/LOGS,newrequest_processing_??????.log,FTP,-,BTORCE-5461
DEDS-166,?????????.bulkFTTPDNs.????????.csv,/deds-host/wca/data/incoming/SMC/LOGS,newrequest_processing_??????.log,FTP,-,BTORCE-5461
DEDS-204,Voice_????????.bpi,/deds-host/wcadata/INCOMING/GENESYS/LOGS,genesys_processing_??????.log,FTP,-,BTRCE-21859
DEDS-204,Agent_????????.txt,/deds-host/wcadata/INCOMING/GENESYS/LOGS,genesys_processing_??????.log,FTP,-,BTRCE-21859
DEDS-204,wipro_??????.????,/deds-host/wcadata/INCOMING/GENESYS/LOGS,genesys_processing_??????.log,FTP,-,BTRCE-21859
DEDS-204,first_??????.????,/deds-host/wcadata/INCOMING/GENESYS/LOGS,genesys_processing_??????.log,FTP,-,BTRCE-21859
DEDS-188,EIP_?????????_??????_*_??????????????.dat.gz,/deds-host/wca/data/incoming/MIS/PAT/LOGS,patreportsprocessing_??????.log,FTPS,-,21CNCE-31600
DEDS-152,PROF_CHNG_REP_DLY_?????????_*_??????????????.xml.Z,/deds-host/wca/data/incoming/MIS/DataProfile/LOGS,dfprocessing_??????.log,FTPS,-,21CNCE-30134
DEDS-152,PERF_CHNG_REP_DLY_?????????_*_??????????????.xml.Z,/deds-host/wca/data/incoming/MIS/DataProfile/LOGS,dfprocessing_??????.log,FTPS,-,21CNCE-30134
DEDS-183,PUR-?????????-??????????-*.csv,/deds-host/wca/data/CP/HIPCOM/LOGS,hipcompur_processing_??????.log,SFTP,hipcom,BTWCE-1795
DEDS-183,SPUR-?????????-*-??????????-*.csv,/deds-host/wca/data/CP/HIPCOM/LOGS,hipcompur_processing_??????.log,SFTP,hipcom,BTWCE-1795
DEDS-183,D???????.D?????????.DIPVS????.Z,/deds-host/logs/wcalls,ipvs_processing_??????.log,FTP,-,BTWCE-1795
DEDS-183,R???????.R?????????.RIPVS????.Z,/deds-host/logs/wcalls,ipvs_processing_??????.log,FTP,-,BTWCE-1795
DEDS-183,M???????.M?????????.MIPVS????.Z,/deds-host/logs/wcalls,ipvs_processing_??????.log,FTP,-,BTWCE-1795
DEDS-183,SSR-?????????-????????-???????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPULL/LOGS,butpull_processing_??????.log,SFTP,hipcom,BTWCE-1795
DEDS-183,EDR-?????????-????????-????????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPULL/LOGS,butpull_processing_??????.log,SFTP,hipcom,BTWCE-1795 
DEDS-183,MEDR-?????????-????????-???????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPULL/LOGS,butpull_processing_??????.log,SFTP,hipcom,BTWCE-1795 
DEDS-183,BUT_DEDS_MEDR_??????_??????????_????????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPUSH/LOGS,butpush_processing_??????.log,-,-BTWCE-1795 
DEDS-183,BUT_DEDS_EDR_????????_??????????_????????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPUSH/LOGS,butpush_processing_??????.log,-,-,BTWCE-1795 
DEDS-183,BUT_DEDS_SSR_??????_??????????_????????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPUSH/LOGS,butpush_processing_??????.log,-,-,BTWCE-1795 
DEDS-206,????????_????_?????????_callbar_out.csv,/deds-host/wcadata/INCOMING/BUT/CALLBAR/CALLBARPUSH/LOGS,barringresponse_push_??????.log,FTPS,-,BTDCE-1426
DEDS-206,????????_????_?????????_callbar_in.csv,/deds-host/wcadata/INCOMING/BUT/CALLBAR/CALLBARPULL/LOGS,callbar_pull_??.log,FTPS,-,BTDCE-1426
DEDS-186,LineQualificationData_?????????_??????????????.tar.gz,/deds-host/wca/data/incoming/YUKON/FIBRE/LOGS,yukon_push_??????.log,FTPS,-,21CNCE-30361
DEDS-186,EIP_??????_?????????_V?_MNH_?_?_????????.dat.gz,/deds-host/wca/data/incoming/MIS/NGA/LOGS,bip_fibre_push_??????.log,FTPS,-,21CNCE-30361
DEDS-328,ALR_D_?????????_*_??????????????.csv.Z,/deds-host/wcadata/INCOMING/BUT/BIPALR/LOGS,but_alr_pull_?????????.log,FTPS,-,UKBCE-41355
DEDS-417,STM_090_??????.*.pgp,/deds-host/wcadata/INCOMING/IME/NEXNETPUSH/LOGS,ime_nexnet_push_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,RUF_090_??????.*.pgp,/deds-host/wcadata/INCOMING/IME/NEXNETPUSH/LOGS,ime_nexnet_push_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,SID_090_??????.*.pgp,/deds-host/wcadata/INCOMING/IME/NEXNETPUSH/LOGS,ime_nexnet_push_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,STM_090_*.*log*,/deds-host/wcadata/INCOMING/IME/NEXNETPULL/LOGS,nexnet_ime_pull_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,RUF_090_*.*log*,/deds-host/wcadata/INCOMING/IME/NEXNETPULL/LOGS,nexnet_ime_pull_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,SID_090_*.*log*,/deds-host/wcadata/INCOMING/IME/NEXNETPULL/LOGS,nexnet_ime_pull_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,STM_090_*.*bad*,/deds-host/wcadata/INCOMING/IME/NEXNETPULL/LOGS,nexnet_ime_pull_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,RUF_090_*.*bad*,/deds-host/wcadata/INCOMING/IME/NEXNETPULL/LOGS,nexnet_ime_pull_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-417,SID_090_*.*bad*,/deds-host/wcadata/INCOMING/IME/NEXNETPULL/LOGS,nexnet_ime_pull_??????.log,SFTP,nexnet,BTGSCE-24324
DEDS-404,mail_migration_result_??????????????.csv,/deds-host/wcadata/INCOMING/CISP/EMS/RESPONSE/LOGS,ems_cisp_pull_??????.log,FTPS,-,BTRCE-41282
DEDS-404,mail_migration_result_??????????????.csv,/deds-host/wcadata/INCOMING/DNP/EMS/RESPONSE/LOGS,ems_dnp_pull_??????.log,FTPS,-,BTRCE-41282
DEDS-263,order_item_????????_??.csv.gz,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log,FTPS,-,BTWCE-19831
DEDS-263,order_item_detail_????????_??.csv.gz,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log,FTPS,-,BTWCE-19831 
DEDS-263,RBM_Product_Charge_????????_????????.dat,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log,FTPS,-,BTWCE-19831 
DEDS-263,RBM_Services_????????_????????.dat,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log,FTPS,-,BTWCE-19831
DEDS-263,?????????_WLR3*_????????_*.gz,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log,FTPS,-,BTWCE-19831 
DEDS-263,ALR_W_?????????_*_??????????????.csv.Z,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log,FTPS,-,BTWCE-19831
DEDS-263,ALR_WCOM_?????????_*_??????????????.csv.Z,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log,FTPS,-,BTWCE-19831
DEDS-209,BT0?????.CIF,/deds-host/wcadata/INCOMING/CSSHQ/POPAYMENT/LOGS,po_css_push_??????.log,FTPS,-,BTRCE-26454
DEDS-209,BT0?????.RSP,/deds-host/wcadata/INCOMING/CSSHQ/PORESPONSE/LOGS,css_po_??????.log,FTPS,-,BTRCE-26454
DEDS-209,CDTHQIN.MVS.HQ.PO.ACKFILE,/deds-host/wcadata/INCOMING/CSSHQ/PORESPONSE/LOGS,css_po_??????.log,FTPS,-BTRCE-26454
DEDS-442,BT1???22119901.DAT,/deds-host/wcadata/INCOMING/CSS/LOGS,css_to_dms_??????.log,FTPS,-,BTWCE-24063
DEDS-442,cp_deds_dms??????????.tar,/deds-host/wcadata/OUTGOING/VOON/LOGS,dmspull_??????.log,FTPS,-,BTWCE-24063
DEDS-442,BT1???22119901.FCO,/deds-host/wcadata/OUTGOING/VOON/LOGS,dmspull_??????.log,FTPS,-,BTWCE-24063
DEDS-442,BT1???22119901.CAR,/deds-host/wcadata/OUTGOING/VOON/LOGS,dmspull_??????.log,FTPS,-,BTWCE-24063
DEDS-442,BT1???22119901.EXP,/deds-host/wcadata/OUTGOING/VOON/LOGS,dmspull_??????.log,FTPS,-,BTWCE-24063
DEDS-442,BT1???22119901.AUD,/deds-host/wcadata/OUTGOING/VOON/LOGS,dmspull_??????.log,FTPS,-,BTWCE-24063
DEDS-442,dms_deds_licensee??????????.tar,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_licensee_??????.log,FTPS,-,BTWCE-24063
DEDS-442,?????????.*.???.????????.dat,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_licensee_??????.log,FTPS,-,BTWCE-24063
DEDS-442,?????????.DQ*.DAT,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_licensee_??????.log,FTPS,-,BTWCE-24063
DEDS-442,?????????.PHDSC*.DAT,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_licensee_??????.log,FTPS,-,BTWCE-24063 
DEDS-442,?????????.FTFYPS.DAT,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_licensee_??????.log,FTPS,-,BTWCE-24063
DEDS-442,dms_deds_cp??????????.tar,/deds-host/wcadata/INCOMING/VOON/LOGS,dmspush_cp_??????.log,FTPS,-,BTWCE-24063
DEDS-412,dlyvadb*.*.????????.dat,/deds-host/wcadata/OUTGOING/DDS/VOON/LOGS,dds_push_??????.log,FTPS,-,BTWCE-24063
DEDS-412,mfcstdah*.*.????????.dat,/deds-host/wcadata/OUTGOING/DDS/VOON/LOGS,dds_push_??????.log,FTPS,-,BTWCE-24063
DEDS-412,phonebook*.*.????????.dat,/deds-host/wcadata/OUTGOING/DDS/VOON/LOGS,dds_push_??????.log,FTPS,-,BTWCE-24063
DEDS-402,CG-NAT_IPReports_?????????_????????.csv,/deds-host/wcadata/INCOMING/AMT/CGNAT/LOGS,cgnat_filemove_??????.log,FTPS,-,21CNCE-49398
DEDS-478,cPlusReports_eubytes_d_????????-??????.tar.gz,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-478,cPlusReports_21C_eubytes_d_????????-??????.tar.gz,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-478,cPlus_metadatafiles_d_????????-??????.tar.gz,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-478,cPlus_21C_metadatafiles_d_????????-??????.tar.gz,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-478,cp_*_eubytes_d_??_??_????.txt,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-478,cp_21C_*_eubytes_d_??_??_????.txt,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-478,cp_*_metadatainfo_d_????????.txt,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-478,cp_21C_*_metadatainfo_d_????????.txt,/deds-host/wca/data/incoming/RMD/CPLUS/LOGS,rmd_filemove_????????.log,SFTP,rmd,BTRCE-32134
DEDS-223,RBM_Usage_Rate_Card_????????_????????.dat.gz,/deds-host/wca/data/incoming/UR/RAFEED/LOGS,trap_logica_pull_??????.log,FTPS,-,BTWCE-15578
DEDS-118,TVCEU_??????_????????????_???.tar,/deds-host/wca/data/incoming/MIS/LTV/LOGS,LTV_processing_??????.log,-,-,-  
DEDS-118,TVCEU_??????_????????????_???.csv,/deds-host/wca/data/incoming/MIS/LTV/LOGS,LTV_processing_??????.log,-,-,-
DEDS-144,IPReports_??????_??????????????.csv,/deds-host/wcadata/INCOMING/AMT/LOGS,IPReports_processing_??????.log,-,-,-
DEDS-149,U???????.U????.U??????????,/deds-host/wcadata/ONM/INCOMING/LOGS,onm_ipex_processing_??????.log,FTP,-,-
DEDS-339,Dq??.dat,/deds-host/logs/wcalls,osis_processing_??????.log,FTP,-,BTWCE-22269
DEDS-220,EIPAL_INBOUND_TP_DATA_??????????????.tar.Z,/deds-host/wcadata/INCOMING/EIPAL/TPULL/LOGS,eipal_pull_??????.log,FTPS,-,BTRCE-18981
DEDS-220,EIP_TP_DATA_??????????????.tar.Z,/deds-host/wcadata/INCOMING/EIPAL/TPUSH/LOGS,eipal_push_??????.log,-,-,BTRCE-18981 
DEDS-220,EIP_TP_DATA_??????????????_success,/deds-host/wcadata/INCOMING/EIPAL/TPUSH/LOGS,eipal_push_??????.log,-,-,BTRCE-18981  
DEDS-220,EIP_TP_DATA_??????????????_failure,/deds-host/wcadata/INCOMING/EIPAL/TPUSH/LOGS,eipal_push_??????.log,-,-,BTRCE-18981   
DEDS-220,IIP_SVC7865_RA_MLR_?.??_DNH_?_?_??????????????.dat,/deds-host/wcadata/INCOMING/EIPAL/TPUSAGE/LOGS,eipal_audit_report_??????.log,-,-,BTRCE-18981  
DEDS-220,IIP_SVC7865_RA_MLR_?.??_DNH_?_?_??????????????.dat,/deds-host/wcadata/INCOMING/EIPAL/TPUSAGE/LOGS,eipal_audit_pull_??????.log,-,-,BTRCE-18981  
DEDS-245,?????????_FVA_????????_?of?.csv.gz,/deds-host/wca/data/incoming/ORBIT/FVA/LOGS,orbit_fva_processing_??????.log,FTPS,-,BTRCE-27426
DEDS-231,OP_BUT_KillSession_????????_?????????.csv,/deds-host/wcadata/INCOMING/BUT/SESSIONKILL/SESSIONPULL/LOGS,but_sk_pull_??????.log,FTPS,-,21CNCE-42958
DEDS-231,OP_BUT_KillSession_Result_????????_?????????.tar,/deds-host/wcadata/INCOMING/BUT/SESSIONKILL/SESSIONPUSH/LOGS,sk_response_??????.log,-,-,21CNCE-42958
DEDS-189,c_ipx_ebc???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982 
DEDS-189,z_ipx_ebc???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982
DEDS-189,c_ipx_ia_cps???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982
DEDS-189,z_ipx_ia_cps???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982
DEDS-189,c_ipx_nts_dest???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982
DEDS-189,z_ipx_nts_dest???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982
DEDS-189,c_ipx_nts_orig???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982
DEDS-189,z_ipx_nts_orig???.???,/deds-host/wcadata/EBCSource/EBCNTS01/logs,EBC_??????_E*.log,FTP,-,BTWCE-15982
DEDS-242,ALR_M_?????????_*_??????????????.csv.Z,/deds-host/wca/data/incoming/MIS/VDCOUT/LOGS,vdc_bip_xfb_??????.log,FTPS,-,BTRCE-26704
DEDS-242,ALR_MCOM_?????????_*_??????????????.csv.Z,/deds-host/wca/data/incoming/MIS/VDCOUT/LOGS,vdc_bip_xfb_??????.log,FTPS,-,BTRCE-26704    
DEDS-242,ALR_D_?????????_*_??????????????.csv.Z,/deds-host/wca/data/incoming/MIS/VDCOUT/LOGS,vdc_bip_xfb_??????.log,FTPS,-,BTRCE-26704
DEDS-242,ALR_DCOM_?????????_*_??????????????.csv.Z,/deds-host/wca/data/incoming/MIS/VDCOUT/LOGS,vdc_bip_xfb_??????.log,FTPS,-,BTRCE-26704
DEDS-242,ALR_W_?????????_*_??????????????.csv.Z,/deds-host/wca/data/incoming/MIS/VDCOUT/LOGS,vdc_bip_xfb_??????.log,FTPS,-,BTRCE-26704
DEDS-242,ALR_WCOM_?????????_*_??????????????.csv.Z,/deds-host/wca/data/incoming/MIS/VDCOUT/LOGS,vdc_bip_xfb_??????.log,FTPS,-,BTRCE-26704
DEDS-302,NPR_EX????_OR_Rpt_?.??_DNH_?_?_??????????????.dat,/deds-host/wca/data/incoming/YUKON/FIBRE/LOGS,yukon_nga_push_??????.log,FTP,-,ORC2MCE-19373
DEDS-394,EIP_?????????_??????_V?_DNH_*_*_??????????????.dat.gz,/deds-host/wca/data/incoming/MIS/PAT/LOGS,patreportsprocessing_??????.log,FTPS,-,BTWCE-22111
DEDS-383,BUT_DEDS_MEDR_??????_??????????_????????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPUSH/LOGS,butpush_processing_??????.log,-,-,BTWCE-23508
DEDS-383,BUT_DEDS_EDR_????????_??????????_????????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPUSH/LOGS,butpush_processing_??????.log,-,-,BTWCE-23508
DEDS-383,BUT_DEDS_SSR_??????_??????????_????????.csv,/deds-host/wcadata/INCOMING/BUT/IPVS/IPVSPUSH/LOGS,butpush_processing_??????.log,-,-,BTWCE-23508
DEDS-461,CDTCSS1.MVS.??.DI*D.*,/deds-host/wcadata/INCOMING/CSS/LOGS,css_to_dms_??????.log,-,-,BTWCE-25231
DEDS-260,?????????_*_????????_*.gz,/deds-host/wca/data/incoming/ORBIT/FVA/LOGS,orbit_fva_processing_??????.log,FTPS,-,ORC2MCE-10378
DEDS-267,ESERVEUNBL*.gz,/deds-host/wcadata/INCOMING/BAL-A/DISEFILES/LOGS,bal_dise_pull_??????.log,SFTP,dise,BTRBCE-8215
DEDS-267,ESERVEBUND*.gz,/deds-host/wcadata/INCOMING/BAL-A/DISEFILES/LOGS,bal_dise_pull_??????.log,SFTP,dise,BTRBCE-8215
DEDS-382,U???????.U????.U??????????,/deds-host/logs/wcalls,FUSION_LOGS_??????.log,FTP,-,BTWCE-21078
DEDS-382,U???????.U?????????.U??????.Z,/deds-host/logs/wcalls,FUSION_LOGS_??????.log,FTP,-,BTWCE-21078
DEDS-815,weekly_inventory_item_??_????????_????????.csv.gz,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,-,-,BTWCE-34097
DEDS-815,weekly_inventory_item_detail_??_????????_????????.csv.gz,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,-,-,BTWCE-34097





:-( 10.1 DEDS-199,??????????????_?????????_FCL.csv.Z,,CDRLog????????.log

168,294-96

DEDS-263,inventory_item_????????_??.csv.gz,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log 
DEDS-263,inventory_item_detail_????????_??.csv.gz,/deds-host/wca/data/outgoing/SRAP/ASSET/LOGS,asset_srap_pull_??????.log
